sudo: false
dist: trusty
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
install:
 - ./ci/travis-prepare.sh
script:
 - make -j2
 - make tapfiles
 - find . -name '*.tap' -print0 | xargs -0 -n1 prove -e cat -f
env:
 - BRBASE=3.16
 - BRBASE=3.16 CMPLR=clang
 - BRBASE=3.16 USR_CXXFLAGS=-std=c++11
 - BRBASE=3.16 USR_CXXFLAGS=-std=c++11 CMPLR=clang
 - BRBASE=3.15
 - BRBASE=3.14
